Fix issue 307 comparing files on two branches
whitesmith/rubycritic pull request #372
Opened 2020-10-03 12:16 UTC by lauratpa

fixes #307 
This bug occurs when a branch that is being compared contains a file that is not present on the other branch.
In this template the files are being compared to one another, but not all files have to have corresponding file on the second branch.

I would have wanted to add a test for this bug, but there seem to be no existing
tests for the template files.

2020-10-03 15:41 UTC, etagwerker requested changes
@lauratpa Thanks for this! It looks really good and easy to understand. 

Could you add a test to reproduce #307 and make sure we don't have any regressions in the future? 😄

2020-10-06 12:10 UTC, lauratpa commented
@etagwerker Sure, once I find a moment I'll try to whip up a test for this issue :)

2022-05-05 08:26 UTC, akolodii commented
@etagwerker  can you please review PR, we want to use rubycritic but cant because of error. when new file was added in PR

2022-05-05 15:56 UTC, etagwerker approved these changes
@lauratpa Great, thanks!

2022-05-05 15:56 UTC, merged